import {
  AngularNodeAppEngine,
  createNodeRequestHandler,
  writeResponseToNodeResponse,
} from '@angular/ssr/node';
// ɵsetAngularAppEngineManifest is the internal API used to register the manifest
// generated by @angular/build:application at build time.
import { ɵsetAngularAppEngineManifest as setAngularAppEngineManifest } from '@angular/ssr';
import express from 'express';
import { fileURLToPath } from 'node:url';
import { dirname, resolve, join } from 'node:path';
import { readFile } from 'node:fs/promises';

const serverDistFolder = dirname(fileURLToPath(import.meta.url));
const browserDistFolder = resolve(serverDistFolder, '../browser');

const engineReady: Promise<AngularNodeAppEngine> = (() => {
  const manifestUrl = new URL('./angular-app-engine-manifest.mjs', import.meta.url).href;
  return (import(/* @vite-ignore */ manifestUrl) as Promise<{ default: any }>).then(
    ({ default: manifest }) => {
      setAngularAppEngineManifest(manifest);
      // allowedHosts allows these production hostnames; NG_ALLOWED_HOSTS env var also works at runtime
      const allowedHosts = (process.env['NG_ALLOWED_HOSTS'] ?? '').split(',').map(h => h.trim()).filter(Boolean);
      return new AngularNodeAppEngine(allowedHosts.length ? { allowedHosts } : undefined);
    },
  );
})();

const app = express();

// Trust reverse proxy headers (ACA, nginx) so Angular SSR gets the real hostname
app.set('trust proxy', true);

app.get('**', express.static(browserDistFolder, {
  maxAge: '1y',
  index: false,
}));

app.get('**', (req, res, next) => {
  engineReady
    .then(engine => engine.handle(req))
    .then((response) => {
      if (response) {
        return writeResponseToNodeResponse(response, res);
      }
      // Angular returns null for CSR routes or SSRF-rejected hosts → serve index.html
      // so the Angular client-side router can take over.
      res.sendFile('index.html', { root: browserDistFolder });
      return;
    })
    .catch(next);
});

const port = process.env['PORT'] || 4000;
app.listen(port, () => {
  console.log(`Node Express server listening on http://localhost:${port}`);
});

export const reqHandler = createNodeRequestHandler((req, res, next) => {
  engineReady
    .then(engine => engine.handle(req))
    .then((response): Promise<void> => {
      if (response) {
        return writeResponseToNodeResponse(response, res);
      }
      // Raw Node.js ServerResponse — read index.html and send it for CSR fallback
      return readFile(join(browserDistFolder, 'index.html')).then((content) => {
        res.setHeader('Content-Type', 'text/html; charset=utf-8');
        res.end(content);
      });
    })
    .catch(next);
});
